# Simple Docker Compose for RAG Chatbot
version: '3.8'

services:
  # Ollama for embeddings
  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  # Your RAG Chatbot
  rag-chatbot:
    build: .
    container_name: rag-chatbot-app
    ports:
      - "8501:8501"
    volumes:
      - ./chroma_db:/app/chroma_db
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama_data: